### ISSUE TITLE
Save value of current IP

### ISSUE THREAD

**Issue by masterwishx** [xavier-hernandez/docker-external-ip#1]
is anyway to add save value of current IP ,that will be (NOT CHANGE) or (SAME) instead of (CHANGE) if IP is not changed ?

**Comment by xavier-hernandez** [comment]
@masterwishx - what is your use case here? You want to save the IP so that it doesn't tell you on docker reboot about a change or you want to statically keep the IP and anything different is a change?

**Comment by masterwishx** [comment]
> want to statically keep the IP and anything different is a change?

Yes

**Comment by masterwishx** [comment]
i meaned to save IP and get message on reboot that its same iP , if its not changed from saved one,
and if IP is changed to get message that its different and (changed).
i hope not complicated the thing :)
Thanks

**Comment by masterwishx** [comment]
any planning on impement this in future ?

**Comment by xavier-hernandez** [comment]
@masterwishx   sorry been busy. I'll take a look at it this weekend.

**Comment by masterwishx** [comment]
> I'll take a look at it this weekend.

Thanks

**Comment by xavier-hernandez** [comment]
@masterwishx this has been completed. Get the latest and check the readme for the new flag and volume you have to add.

```yaml
external_ip:
    image: xavierh/external-ip:latest
    container_name: external_ip
    restart: always
    environment:
        - TZ=America/New_York
        - RECOVERY_ALERT=True/False #optional, default is False
        - DELAY=5m #optional, default is 5 minutes
        - PROVIDER=CLOUDFLARE #optional, default is cloudflare
        - NOTIFICATION_TYPE=PUSHOVER #optional
        - PUSHOVER_TOKEN=token #optional
        - PUSHOVER_USER=user #optional
        - PUSHOVER_TITLE=title #optional, if using PUSHOVER
        - SAVE_IP=True #optional
    volume:
        - /path/to/data:/stor-external-ip #optional but required if using SAVE_IP
 ```
